package com.tianxiao.faas.mapper.model;

import java.util.Date;

public class FaaSServiceModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.id
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.service_name
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.service_desc
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String serviceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.over_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer overTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.max_qps
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer maxQps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.language
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.creator
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.version
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.status
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.cache_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer cacheTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.modifier
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.group
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.create_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.edit_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.is_deleted
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_services.script
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    private String script;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.id
     *
     * @return the value of t_services.id
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.id
     *
     * @param id the value for t_services.id
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.service_name
     *
     * @return the value of t_services.service_name
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.service_name
     *
     * @param serviceName the value for t_services.service_name
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.service_desc
     *
     * @return the value of t_services.service_desc
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.service_desc
     *
     * @param serviceDesc the value for t_services.service_desc
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.over_time
     *
     * @return the value of t_services.over_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.over_time
     *
     * @param overTime the value for t_services.over_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setOverTime(Integer overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.max_qps
     *
     * @return the value of t_services.max_qps
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getMaxQps() {
        return maxQps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.max_qps
     *
     * @param maxQps the value for t_services.max_qps
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setMaxQps(Integer maxQps) {
        this.maxQps = maxQps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.language
     *
     * @return the value of t_services.language
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.language
     *
     * @param language the value for t_services.language
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.creator
     *
     * @return the value of t_services.creator
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.creator
     *
     * @param creator the value for t_services.creator
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.version
     *
     * @return the value of t_services.version
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.version
     *
     * @param version the value for t_services.version
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.status
     *
     * @return the value of t_services.status
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.status
     *
     * @param status the value for t_services.status
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.cache_time
     *
     * @return the value of t_services.cache_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getCacheTime() {
        return cacheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.cache_time
     *
     * @param cacheTime the value for t_services.cache_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setCacheTime(Integer cacheTime) {
        this.cacheTime = cacheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.modifier
     *
     * @return the value of t_services.modifier
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.modifier
     *
     * @param modifier the value for t_services.modifier
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.group
     *
     * @return the value of t_services.group
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.group
     *
     * @param group the value for t_services.group
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.create_time
     *
     * @return the value of t_services.create_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.create_time
     *
     * @param createTime the value for t_services.create_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.edit_time
     *
     * @return the value of t_services.edit_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.edit_time
     *
     * @param editTime the value for t_services.edit_time
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.is_deleted
     *
     * @return the value of t_services.is_deleted
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.is_deleted
     *
     * @param isDeleted the value for t_services.is_deleted
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_services.script
     *
     * @return the value of t_services.script
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public String getScript() {
        return script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_services.script
     *
     * @param script the value for t_services.script
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    public void setScript(String script) {
        this.script = script == null ? null : script.trim();
    }
}