package com.tianxiao.faas.mapper.dao;

import com.tianxiao.faas.mapper.model.FaaSServiceModel;
import com.tianxiao.faas.mapper.model.FaaSServiceModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaaSServiceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    long countByExample(FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int deleteByExample(FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int insert(FaaSServiceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int insertSelective(FaaSServiceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    List<FaaSServiceModel> selectByExampleWithBLOBs(FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    List<FaaSServiceModel> selectByExample(FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") FaaSServiceModel record, @Param("example") FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") FaaSServiceModel record, @Param("example") FaaSServiceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_services
     *
     * @mbg.generated Fri Nov 13 15:28:28 CST 2020
     */
    int updateByExample(@Param("record") FaaSServiceModel record, @Param("example") FaaSServiceModelExample example);
}